apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb-config
  namespace: lamp-stack
data:
  init-db.sql: |
    CREATE DATABASE test;

    USE test;

    CREATE TABLE messages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(50) NOT NULL,
        content TEXT NOT NULL
    );

    INSERT INTO messages (username, content) VALUES ('user1', 'Hello, world!');
    INSERT INTO messages (username, content) VALUES ('user2', 'This is a test message.');
    INSERT INTO messages (username, content) VALUES ('user3', 'Another random message.');